apiVersion: v1
kind: Service
metadata:
  name: waya-repository
  labels:
    app: waya-repository
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: waya-repository
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waya-repository
  labels:
    app: waya-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waya-repository
  template:
    metadata:
      labels:
        app: waya-repository
    spec:
      containers:
      - name: waya-repository
        image: 863852973330.dkr.ecr.eu-west-2.amazonaws.com/waya-repository:imgtag
        envFrom:
        - configMapRef:
            name: common-services-config
        ports: 
        - name: http
          containerPort: 80 
        volumeMounts:
        - name: config-file
          mountPath: "/app/application-cfgprofile.yml"  # "secret-file" file will be created in "/app" directory
          subPath: application.yml
        - name: tz-lagos
          mountPath: /etc/localtime
      volumes:
        - name: config-file
          secret:
            secretName: waya-repository-config-file # name of the Secret
        - name: tz-lagos
          hostPath:
            path: /usr/share/zoneinfo/Africa/Lagos
