server:
  port: ${TEMP_SERVER_PORT:80}
  servlet:
    context-path: /
spring:
   application:
      name: temporal-service
      
   jpa:
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
          dialect: ${TEMP_SVC_DB_DIALECT:org.hibernate.dialect.H2Dialect}
          show-sql: true
          jdbc:
            time_zone: UTC
     open-in-view: false
    
   devtools:
       livereload:
           enabled: false
   jackson:
      serialization:
         fail-on-empty-beans: false
         
   datasource:
        url:  ${TEMP_SVC_DB_URL:jdbc:h2:mem:dbTemp}
        username: ${TEMP_SVC_DB_USERNAME:sa}
        password: ${TEMP_SVC_DB_PASSWORD:sa}
        driver-class-name: ${TEMP_SVC_DB_DRIVER:org.h2.Driver}
   flyway:
      baselineOnMigrate: true
      locations: classpath:db/migration
      schemas: public
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-service/eureka}
    service-url:
      default-zone: ${EUREKA_SERVER_URL:http://eureka-service/eureka}
  instance:
    preferIpAddress: true

waya:
   wallet:
       auth: AUTHENTICATION-SERVICE
       authurl: ${CONFIG_BASEURL_AUTH:https://services.staging.wayabank.ng/auth-service/api/v1} 
       mifos: MIFOS-WALLET-SERVICE
       mifosurl: ${CONFIG_BASEURL_MWALLET:https://services.staging.wayabank.ng/wallet-service}
       productcode: ${CONFIG_PRODUCT_SAVINGS:SB601}
       commissioncode: ${CONFIG_PRODUCT_COMMISSION:SB901}
       wayaglCode: ${CONFIG_PRODUCT_SAVINGS_CODE:21200}
       wayacommglCode: ${CONFIG_PRODUCT_COMMISSION_CODE:21105}
       
   card:
     cardurl: ${CONFIG_BASEURL_CARD:https://services.staging.wayabank.ng/card-service}
     service: CARD-SERVICE
     contacturl: ${CONFIG_BASEURL_CONTACT:https://services.staging.wayabank.ng/contact-service}
   contact:
      service: CONTACT-SERVICE
   account:
       accounturl: ${CONFIG_BASEURL_VIRACCOUNT:https://services.staging.wayabank.ng/account-service}
       service: ACCOUNT-SERVICE
#   sms:
#     atalking: ${AFRICATALKING}
#     infobip: ${INFOBIP}
#     twilio: ${TWILIO}
   notification:
      service: NOTIFICATION-SERVICE
      notificationurl: ${CONFIG_BASEURL_NOTIFICATION:https://services.staging.wayabank.ng/notification-service}
   receipt:
      service: RECEIPT-SERVICE
      receipturl: ${CONFIG_BASEURL_RECEIPT:https://services.staging.wayabank.ng/transaction-receipt}
   service:
     username: tbaadm@wayapaychat.com
     password: fintemp@#123
     keysecret: d2F5YXByb2QxNzI2MjAyMg==
     keytemporal: MWtLMW01czA3SFpMc2dpRWlhR2psQTV2SjdISTJqNUcxU3d5UmlKbmFXMTA2alJnK1NuVzBBUDMySTVKQ0hlRQ==
     keymifos: bzVkbElFTWl2MmkwUEcxNFd0eXU4ZzV2SjdISTJqNUcxU3d5UmlKbmFXMnROQWE0V1drWDRMY1EyZ2R4d2hXRQ==